# Generated by Django 3.2.6 on 2021-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapannotationpoint',
            name='wishList',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(related_name='items', to='places.MapAnnotationPoint'),
        ),
    ]
