# Generated by Django 3.2.6 on 2021-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210826_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapannotationpoint',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapannotationpoint',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
