# Generated by Django 3.2.6 on 2021-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210826_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapannotationpoint',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mapannotationpoint',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
