# Generated by Django 3.2.6 on 2021-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20210826_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapannotationpoint',
            name='latitude',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mapannotationpoint',
            name='longitude',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mapannotationpoint',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mapannotationpoint',
            name='streetAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mapannotationpoint',
            name='subtitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mapannotationpoint',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
